### ISSUE TITLE
Add instructions

### ISSUE THREAD

**Issue by zenorocha** [dracula/xchat#1]
Hey @beefsack, could you share the instructions to install this theme? I really want to add this to the draculatheme.com website ;)

**Comment by zenorocha** [comment]
https://github.com/dracula/xchat/commit/894c052afd85ec68d6af5a9c14cbc1de7067d906 ;D

**Comment by beefsack** [comment]
Hi @zenorocha, sorry I didn't get around to this, it completely slipped me by 😞

Thanks for sorting it out!

**Comment by zenorocha** [comment]
No problem at all @beefsack ;)
