### ISSUE TITLE
Hexchat

### ISSUE THREAD

**Issue by amittel** [dracula/xchat#3]
Hi!
Just installed Hexchat and it uses the same `hct` file for themes. So it may be a good idea to put Hexchat also on the frontpage.
An extra repo shouldn't be necessary in my opinion.

I had to google and just tried it out in the end if it works.

**Comment by beefsack** [comment]
Yeah that's right, I've actually used this with Hexchat previously. Hexchat supports more colouring options though so I believe there may be a case that warrants having a special theme for it.
